# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=64, verbose_name='\u5bc6\u7801')),
                ('email', models.CharField(max_length=64, verbose_name='email')),
                ('gender', models.BooleanField(default=True, verbose_name='\u6027\u522b')),
                ('birthdate', models.CharField(max_length=60, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('marriage', models.CharField(max_length=60, verbose_name='\u5a5a\u59fb\u72b6\u51b5')),
                ('education', models.CharField(max_length=32, verbose_name='\u5b66\u5386')),
                ('height', models.IntegerField(default=0, verbose_name='\u8eab\u9ad8/cm')),
                ('weight', models.IntegerField(default=0, verbose_name='\u4f53\u91cd/kg')),
                ('region', models.CharField(max_length=20, verbose_name='\u5730\u533a')),
                ('income', models.CharField(max_length=64, verbose_name='\u6536\u5165')),
                ('phone_num', models.CharField(max_length=20, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('id_card_num', models.CharField(max_length=64, verbose_name='\u8eab\u4efd\u8bc1')),
                ('head_img', models.ImageField(null=True, upload_to='uploads/imgs/', verbose_name='\u5934\u50cf')),
                ('head_thumb_img', models.ImageField(null=True, upload_to='uploads/thumbs/', verbose_name='\u5934\u50cf\u7f29\u7565\u56fe')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('introduce', models.TextField(max_length=1000, verbose_name='\u4ecb\u7ecd')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
    ]
