# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=64, verbose_name='\u5bc6\u7801')),
                ('email', models.CharField(max_length=64, verbose_name='email')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
