# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20180830_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobil_phone', models.CharField(default='', max_length=20, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('qq', models.CharField(default='', max_length=20, verbose_name='QQ\u53f7\u7801')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('wechat', models.CharField(default='', max_length=60, verbose_name='\u5fae\u4fe1')),
                ('webo', models.CharField(default='', max_length=60, verbose_name='\u5fae\u535a')),
                ('site', models.CharField(default='', max_length=120, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('zip_code', models.CharField(default='', max_length=32, verbose_name='\u90ae\u7f16')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.LoginInfo')),
            ],
            options={
                'verbose_name_plural': '\u8054\u7cfb\u8d44\u6599',
            },
        ),
        migrations.CreateModel(
            name='StudyWordLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_style', models.CharField(default='', max_length=120, verbose_name='\u516c\u53f8\u7c7b\u578b')),
                ('salary_describe', models.CharField(default='', max_length=120, verbose_name='\u6536\u5165\u63cf\u8ff0')),
                ('work_situation', models.CharField(default='', max_length=120, verbose_name='\u5de5\u4f5c\u60c5\u51b5')),
                ('company_name', models.CharField(default='', max_length=120, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('educational_background', models.CharField(default='', max_length=60, verbose_name='\u5b66\u5386')),
                ('major_style', models.CharField(default='', max_length=120, verbose_name='\u4e13\u4e1a\u7c7b\u578b')),
                ('school', models.CharField(default='', max_length=120, verbose_name='\u5b66\u6821\u7c7b\u578b')),
                ('enrolment_time', models.CharField(default='', max_length=60, verbose_name='\u5165\u5b66\u65f6\u95f4')),
                ('language', models.CharField(default='', max_length=60, verbose_name='\u8bed\u8a00\u80fd\u529b')),
                ('family_num', models.CharField(default='', max_length=60, verbose_name='\u5bb6\u4e2d\u6392\u884c')),
                ('consumption_level', models.CharField(default='', max_length=60, verbose_name='\u6d88\u8d39\u6c34\u5e73')),
                ('is_smoking', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5438\u70df')),
                ('is_drink', models.BooleanField(default=False, verbose_name='\u662f\u5426\u559d\u9152')),
                ('faith', models.CharField(default='', max_length=60, verbose_name='\u5b97\u6559\u4fe1\u4ef0')),
                ('take_exercise', models.CharField(default='', max_length=60, verbose_name='\u4f53\u80b2\u953b\u70bc')),
                ('work_rest', models.CharField(default='', max_length=120, verbose_name='\u4f5c\u606f\u4e60\u60ef')),
                ('want_kid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u8981\u5b69\u5b50')),
                ('with_parents_live', models.BooleanField(default=False, verbose_name='\u662f\u5426\u548c\u7236\u6bcd\u540c\u4f4f')),
                ('make_romantic', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5236\u9020\u6d6a\u6f2b')),
                ('live_skill', models.CharField(default='', max_length=120, verbose_name='\u751f\u6d3b\u6280\u80fd')),
                ('like_sport', models.CharField(default='', max_length=120, verbose_name='\u559c\u6b22\u8fd0\u52a8')),
                ('like_food', models.CharField(default='', max_length=120, verbose_name='\u559c\u6b22\u98df\u7269')),
                ('like_book', models.CharField(default='', max_length=120, verbose_name='\u559c\u6b22\u4e66\u7c4d')),
                ('like_movie', models.CharField(default='', max_length=120, verbose_name='\u559c\u6b22\u7535\u5f71')),
                ('avocation', models.CharField(default='', max_length=120, verbose_name='\u4e1a\u4f59\u7231\u597d')),
                ('like_travel', models.CharField(default='', max_length=120, verbose_name='\u559c\u6b22\u65c5\u6e38')),
                ('like_program', models.CharField(default='', max_length=120, verbose_name='\u559c\u6b22\u8282\u76ee')),
                ('introduce', models.TextField(default='', verbose_name='\u5185\u5fc3\u72ec\u767d')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.LoginInfo')),
            ],
            options={
                'verbose_name_plural': '\u5b66\u4e60\u5de5\u4f5c\u751f\u6d3b',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=True, verbose_name='\u6027\u522b')),
                ('birthday', models.CharField(default='', max_length=60, verbose_name='\u751f\u65e5')),
                ('constellation', models.CharField(default='', max_length=12, verbose_name='\u661f\u5ea7')),
                ('zodiac', models.CharField(default='', max_length=12, verbose_name='\u751f\u8096')),
                ('marray_state', models.CharField(default='\u672a\u5a5a', max_length=32, verbose_name='\u5a5a\u59fb\u72b6\u6001')),
                ('height', models.IntegerField(default=160, max_length=8, verbose_name='\u8eab\u9ad8')),
                ('blood_type', models.CharField(default='', max_length=32, verbose_name='\u8840\u578b')),
                ('have_kid', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709\u5c0f\u5b69')),
                ('nationality', models.CharField(default='\u4e2d\u56fd', max_length=60, verbose_name='\u56fd\u7c4d')),
                ('household_register', models.CharField(default='', max_length=60, verbose_name='\u6237\u7c4d')),
                ('live_area', models.CharField(default='', max_length=60, verbose_name='\u5c45\u4f4f\u5730\u533a')),
                ('dating_type', models.CharField(default='', max_length=60, verbose_name='\u4ea4\u53cb\u7c7b\u578b')),
                ('personality', models.CharField(default='', max_length=60, verbose_name='\u4e2a\u6027')),
                ('national', models.CharField(default='', max_length=60, verbose_name='\u540d\u65cf')),
                ('career', models.CharField(default='', max_length=60, verbose_name='\u804c\u4e1a')),
                ('salary', models.CharField(default='', max_length=120, verbose_name='\u85aa\u8d44')),
                ('house_situation', models.CharField(default='', max_length=120, verbose_name='\u4f4f\u623f\u60c5\u51b5')),
                ('have_car', models.BooleanField(default=False, verbose_name='\u8d2d\u8f66\u60c5\u51b5')),
                ('weight', models.CharField(default='0', max_length=10, verbose_name='\u4f53\u91cd')),
                ('appearance', models.CharField(default='', max_length=60, verbose_name='\u5916\u8c8c')),
                ('glamour_place', models.CharField(default='', max_length=60, verbose_name='\u9b45\u529b\u90e8\u4f4d')),
                ('hairstyle', models.CharField(default='', max_length=60, verbose_name='\u53d1\u578b')),
                ('haircolor', models.CharField(default='', max_length=60, verbose_name='\u53d1\u8272')),
                ('facestyle', models.CharField(default='', max_length=60, verbose_name='\u8138\u578b')),
                ('bodystyle', models.CharField(default='', max_length=60, verbose_name='\u4f53\u578b')),
                ('img', models.ImageField(null=True, upload_to='uploads/imgs/', verbose_name='\u5934\u50cf')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.LoginInfo')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u57fa\u672c\u4fe1\u606f',
            },
        ),
    ]
