# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_auto_20180831_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studywordlive',
            name='avocation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '\u97f3\u4e50'), (1, '\u4f53\u80b2'), (2, '\u5199\u4f5c'), (3, '\u6e38\u620f'), (4, '\u65c5\u6e38')], max_length=120, verbose_name='\u4e1a\u4f59\u7231\u597d'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='company_style',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u653f\u5e9c\u673a\u6784'), (2, '\u4e16\u754c500\u5f3a'), (3, '\u5916\u4f01'), (4, '\u56fd\u6709\u4f01\u4e1a'), (5, '\u5176\u4ed6')], default='0', max_length=120, verbose_name='\u516c\u53f8\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='consumption_level',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u7f8e\u98df'), (2, '\u670d\u88c5'), (3, '\u65c5\u6e38'), (4, '\u5176\u4ed6')], default='0', max_length=60, verbose_name='\u6700\u5927\u6d88\u8d39'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='educational_background',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u4e2d\u4e13\u53ca\u4e00\u4e0b'), (2, '\u5927\u4e13'), (3, '\u672c\u79d1'), (4, '\u672c\u79d1\u4ee5\u4e0a')], default='0', max_length=60, verbose_name='\u5b66\u5386'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='enrolment_time',
            field=models.CharField(default='', max_length=60, verbose_name='\u5165\u5b66\u5e74\u4efd'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='faith',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u65e0\u5b97\u6559\u4fe1\u4ef0'), (2, '\u4f5b\u6559'), (3, '\u57fa\u7763\u6559'), (4, '\u4f0a\u65af\u5170\u6559'), (5, '\u5176\u4ed6')], default='1', max_length=60, verbose_name='\u5b97\u6559\u4fe1\u4ef0'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='family_num',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u8001\u5927'), (2, '\u8001\u4e8c'), (3, '\u8001\u4e09'), (4, '\u8001\u56db'), (5, '\u8001\u4e94\u4ee5\u53ca\u66f4\u5c0f')], default='0', max_length=60, verbose_name='\u5bb6\u4e2d\u6392\u884c'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '\u6c49\u8bed'), (2, '\u82f1\u8bed'), (3, '\u65e5\u8bed'), (4, '\u6cd5\u8bed'), (5, '\u8d8a\u5357\u8bed'), (6, '\u5176\u4ed6')], max_length=60, verbose_name='\u8bed\u8a00\u80fd\u529b'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='like_book',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '\u6821\u56ed\u9752\u6625'), (1, '\u6587\u5b66'), (2, '\u5386\u53f2\u4f20\u8bb0'), (3, '\u65c5\u6e38'), (4, '\u5176\u4ed6')], max_length=120, verbose_name='\u559c\u6b22\u4e66\u7c4d'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='like_food',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '\u4e2d\u56fd\u83dc'), (1, '\u65e5\u672c\u83dc'), (2, '\u6cf0\u56fd\u83dc'), (3, '\u6cd5\u56fd\u83dc'), (4, '\u5176\u4ed6')], max_length=120, verbose_name='\u559c\u6b22\u98df\u7269'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='like_movie',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '\u60ac\u7591\u63a8\u7406'), (1, '\u7231\u60c5'), (2, '\u559c\u5267'), (3, '\u52a8\u753b'), (4, '\u897f\u90e8')], max_length=120, verbose_name='\u559c\u6b22\u7535\u5f71'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='like_program',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '\u653f\u6cbb\u65f6\u95f4'), (1, '\u5a31\u4e50\u516b\u5366'), (2, '\u4f53\u80b2\u8d5b\u4e8b'), (3, '\u6d77\u9009\u6d3b\u52a8')], max_length=120, verbose_name='\u559c\u6b22\u8282\u76ee'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='like_sport',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '\u8db3\u7403'), (1, '\u7bee\u7403'), (2, '\u6392\u7403'), (3, '\u7f51\u7403'), (4, '\u7fbd\u6bdb\u7403'), (5, '\u5176\u4ed6')], max_length=120, verbose_name='\u559c\u6b22\u8fd0\u52a8'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='like_travel',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '\u540d\u5c71\u53e4\u5239'), (1, '\u79c0\u7f8e\u5c71\u6c34'), (2, '\u5c0f\u6865\u6d41\u6c34'), (3, '\u9ad8\u539f\u96ea\u57df')], max_length=120, verbose_name='\u559c\u6b22\u65c5\u6e38'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='live_skill',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '\u5b9e\u73b0\u4e2a\u4eba\u76ee\u6807'), (1, '\u7ef4\u62a4\u670b\u53cb\u5708\u5173\u7cfb'), (2, '\u88c5\u4fee\u623f\u5c4b'), (3, '\u5fd7\u613f\u8005'), (4, '\u4fdd\u6301\u751f\u6d3b\u89c4\u5f8b'), (5, '\u7406\u8d22'), (6, '\u5176\u4ed6')], max_length=120, verbose_name='\u751f\u6d3b\u6280\u80fd'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='major_style',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u8ba1\u7b97\u673a\u7c7b'), (2, '\u91d1\u878d\u7c7b'), (3, '\u4e2d\u6587\u7c7b'), (4, '\u5176\u4ed6')], default='0', max_length=120, verbose_name='\u4e13\u4e1a\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='salary_describe',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u798f\u5229\u4f18\u8d8a'), (2, '\u6295\u8d44\u9ad8\u56de\u62a5'), (3, '\u5176\u4ed6')], default='0', max_length=120, verbose_name='\u6536\u5165\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='take_exercise',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u6bcf\u5929\u953b\u70bc'), (2, '\u6bcf\u5468\u51e0\u6b21'), (3, '\u6bcf\u6708\u51e0\u6b21'), (4, '\u4ece\u4e0d\u953b\u70bc')], default='0', max_length=60, verbose_name='\u4f53\u80b2\u953b\u70bc'),
        ),
        migrations.AlterField(
            model_name='studywordlive',
            name='work_situation',
            field=models.CharField(choices=[(0, '\u8bf7\u9009\u62e9'), (1, '\u8f7b\u677e\u7a33\u5b9a'), (2, '\u5de5\u4f5c\u81ea\u7531'), (3, '\u5176\u4ed6')], default='0', max_length=120, verbose_name='\u5de5\u4f5c\u60c5\u51b5'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weight',
            field=models.CharField(choices=[[30, '30KG'], [31, '31KG'], [32, '32KG'], [33, '33KG'], [34, '34KG'], [35, '35KG'], [36, '36KG'], [37, '37KG'], [38, '38KG'], [39, '39KG'], [40, '40KG'], [41, '41KG'], [42, '42KG'], [43, '43KG'], [44, '44KG'], [45, '45KG'], [46, '46KG'], [47, '47KG'], [48, '48KG'], [49, '49KG'], [50, '50KG'], [51, '51KG'], [52, '52KG'], [53, '53KG'], [54, '54KG'], [55, '55KG'], [56, '56KG'], [57, '57KG'], [58, '58KG'], [59, '59KG'], [60, '60KG'], [61, '61KG'], [62, '62KG'], [63, '63KG'], [64, '64KG'], [65, '65KG'], [66, '66KG'], [67, '67KG'], [68, '68KG'], [69, '69KG'], [70, '70KG'], [71, '71KG'], [72, '72KG'], [73, '73KG'], [74, '74KG'], [75, '75KG'], [76, '76KG'], [77, '77KG'], [78, '78KG'], [79, '79KG'], [80, '80KG'], [81, '81KG'], [82, '82KG'], [83, '83KG'], [84, '84KG'], [85, '85KG'], [86, '86KG'], [87, '87KG'], [88, '88KG'], [89, '89KG'], [90, '90KG'], [91, '91KG'], [92, '92KG'], [93, '93KG'], [94, '94KG'], [95, '95KG'], [96, '96KG'], [97, '97KG'], [98, '98KG'], [99, '99KG'], [100, '100KG'], [101, '101KG'], [102, '102KG'], [103, '103KG'], [104, '104KG'], [105, '105KG'], [106, '106KG'], [107, '107KG'], [108, '108KG'], [109, '109KG'], [110, '110KG'], [111, '111KG'], [112, '112KG'], [113, '113KG'], [114, '114KG'], [115, '115KG'], [116, '116KG'], [117, '117KG'], [118, '118KG'], [119, '119KG'], [120, '120KG'], [121, '121KG'], [122, '122KG'], [123, '123KG'], [124, '124KG'], [125, '125KG'], [126, '126KG'], [127, '127KG'], [128, '128KG'], [129, '129KG'], [130, '130KG'], [131, '131KG'], [132, '132KG'], [133, '133KG'], [134, '134KG'], [135, '135KG'], [136, '136KG'], [137, '137KG'], [138, '138KG'], [139, '139KG'], [140, '140KG'], [141, '141KG'], [142, '142KG'], [143, '143KG'], [144, '144KG'], [145, '145KG'], [146, '146KG'], [147, '147KG'], [148, '148KG'], [149, '149KG']], default='50', max_length=10, verbose_name='\u4f53\u91cd'),
        ),
    ]
