# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('activitytype', models.CharField(max_length=32, verbose_name='\u6d3b\u52a8\u7c7b\u578b')),
                ('region', models.CharField(max_length=32, verbose_name='\u5730\u533a')),
                ('cover', models.ImageField(null=True, upload_to='static/imgs/img/', verbose_name='\u5c01\u9762')),
                ('pub_date', models.DateTimeField(verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('endtime', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('mancount', models.IntegerField(verbose_name='\u7537\u62a5\u540d\u4eba\u6570')),
                ('womancount', models.IntegerField(verbose_name='\u5973\u62a5\u540d\u4eba\u6570')),
                ('status', models.BooleanField(verbose_name='\u662f\u5426\u7ed3\u675f')),
                ('introduce', models.TextField(null=True, verbose_name='\u6d3b\u52a8\u4ecb\u7ecd')),
                ('content', tinymce.models.HTMLField(verbose_name='\u6d3b\u52a8\u8be6\u60c5')),
            ],
            options={
                'verbose_name_plural': '\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('phone', models.CharField(max_length=11, verbose_name='\u516c\u53f8\u7535\u8bdd')),
                ('site', models.CharField(max_length=32, verbose_name='\u516c\u53f8\u5730\u5740')),
                ('email', models.EmailField(max_length=254, verbose_name='\u516c\u53f8\u90ae\u7bb1')),
                ('content', tinymce.models.HTMLField(default='', verbose_name='\u516c\u53f8\u4ecb\u7ecd')),
                ('contactus', tinymce.models.HTMLField(default='', verbose_name='\u8054\u7cfb\u6211\u4eec')),
                ('recruit', tinymce.models.HTMLField(default='', verbose_name='\u9ad8\u85aa\u62db\u8058')),
                ('disclaimer', tinymce.models.HTMLField(default='', verbose_name='\u514d\u8d23\u7533\u660e')),
                ('promise', tinymce.models.HTMLField(default='', verbose_name='\u90d1\u91cd\u627f\u8bfa')),
                ('notes', tinymce.models.HTMLField(default='', verbose_name='\u4ea4\u53cb\u987b\u77e5')),
                ('privacyprotect', tinymce.models.HTMLField(default='', verbose_name='\u4fdd\u62a4\u9690\u79c1')),
            ],
            options={
                'verbose_name_plural': '\u516c\u53f8\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='NewsReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('writer', models.CharField(max_length=32, verbose_name='\u4f5c\u8005')),
                ('browse', models.IntegerField(verbose_name='\u6d4f\u89c8')),
                ('content', tinymce.models.HTMLField(verbose_name='\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u65b0\u95fb\u9605\u8bfb',
            },
        ),
        migrations.CreateModel(
            name='SuccessCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('status', models.CharField(max_length=32, verbose_name='\u72b6\u6001')),
                ('browse', models.IntegerField(verbose_name='\u6d4f\u89c8')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('cover', models.ImageField(null=True, upload_to='static/imgs/img/', verbose_name='\u5c01\u9762')),
                ('content', tinymce.models.HTMLField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name_plural': '\u6210\u529f\u6848\u4f8b',
            },
        ),
    ]
